## Estadística Aplicada
Sesión 2 - 9 agosto

Karla Mariana Ley Acero 2076201


Una lista en python es una colección de objetos que pueden ser de distinto tipo 

In [1]:
alumno1 = ['Juan', 'Perez', 17]

In [2]:
type (alumno1)

list

In [3]:
alumno1

['Juan', 'Perez', 17]

In [4]:
estadistica_g4 = ['Dania', 'Karla', 'Vania', 'Eugenia']

In [5]:
estadistica_g4

['Dania', 'Karla', 'Vania', 'Eugenia']

In [6]:
#Seleccionar elementos por su posición, python empieza a contar desde cero 
estadistica_g4[2]

'Vania'

In [7]:
estadistica_g4[0]

'Dania'

In [10]:
estadistica_g4[0] , estadistica_g4[2]

('Dania', 'Vania')

In [12]:
#Desde una posición hasta la otra
#el tres lo toma como el elemento en donde se detiene, entonces no lo considera
estadistica_g4[0:3]

['Dania', 'Karla', 'Vania']

In [13]:
yo_enFCFM = ['Karla', 'LA', 7, 93]

In [14]:
mi_promedio = yo_enFCFM[3]
mi_carrera = yo_enFCFM[1]

In [15]:
print(mi_carrera, mi_promedio)

LA 93


## Librerias / Modulos / Paquetes

Una librería en Python es un conjunto de códigos que le dice a Python como hacer determinadas cosas 

    Pandas indica como manejar dataframes (en filas y columnas)
    Scipy manjea temas de probabilidad
    Matploblib es un graficador
    Statsmodels estima modelos estadísticos 
Las tres obligatorias son:
1. Numpy porque trabajas con números
2. Pandas (datos en tablas)
3. Matploblib porque gráficas

Una librería primero se instala (única vez), y luego se le indica a Python que la use

Vamos a instalar primero la librería de yfinance que nos permite conectarnos a Yahoo Finance

In [16]:
pip install yfinance

                                              0.0/63.2 kB ? eta -:--:--
     ------                                   10.2/63.2 kB ? eta -:--:--
     --------------------------------------   61.4/63.2 kB 3.2 MB/s eta 0:00:01
     --------------------------------------   61.4/63.2 kB 3.2 MB/s eta 0:00:01
     -------------------------------------- 63.2/63.2 kB 481.2 kB/s eta 0:00:00
                                              0.0/10.6 MB ? eta -:--:--
                                              0.1/10.6 MB 2.2 MB/s eta 0:00:05
                                              0.1/10.6 MB 1.8 MB/s eta 0:00:06
                                              0.2/10.6 MB 1.6 MB/s eta 0:00:07
     -                                        0.3/10.6 MB 1.5 MB/s eta 0:00:07
     -                                        0.3/10.6 MB 1.4 MB/s eta 0:00:08
     -                                        0.4/10.6 MB 1.5 MB/s eta 0:00:07
     -                                        0.5/10.6 MB 1.5 MB/s et

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:
#Le damos un apodo para que el código sea más fácil de leer0
import yfinance as yf

In [21]:
#función para descargar precio de acciones
yf.download('APPL' , '2019-01-01' , '2020-12-31')
#le faltan los parametros de la funcion

[*********************100%***********************]  1 of 1 completed


1 Failed download:
['APPL']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2019-01-01 -> 2020-12-31)')


Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

## NUMPY

Numpy sirve para manejar numeros en Python ya sea matrices, vectores, etc. 

Siempre se importara de la siguiente forma:

import numpy as np

In [22]:
import numpy as np

Si da error hay que instalar numpy

La estructura básica de Numpy son los arreglos (arrays), que son una colección de objetos del mismo tipo (numericos)

In [23]:
#crear una lista con la venta de la semana de paletas de helado 
ventas = [12, 23, 34, 45, 56]

In [24]:
#convertir lista en arreglo de numpy
#array convierte una lista en un arreglo
ventas = np.array(ventas)
#Guardo en ventas para actualizar su contenido

In [25]:
type(ventas)

numpy.ndarray

In [26]:
#ventas ya es un arreglo de numpy, ya le puedo asignar las funciones de numpy
#solo puedo aplicar las funciones de numpy en arreglos

#Por ejemplo, la media

np.mean(ventas)

34.0

In [27]:
#Suma

np.sum(ventas)

170

In [28]:
#Ventas mas grandes

np.max(ventas)

56

In [29]:
#Valor mínimo

np.min(ventas)

12

In [30]:
#Python usa una formula de varianza con ddof si ddof= 0 varianza normal y si es igual a 1 es muestral

#Varianza poblacional 
#Si no le pongo ddof python supone que es cero
np.var(ventas)

242.0

In [32]:
#Varianza muestral
np.var(ventas, ddof=1)

302.5

In [33]:
#Desviación estándar poblacional
np.std(ventas)

15.556349186104045

In [34]:
#Desviación estándar muestral
np.std(ventas, ddof=1)

17.392527130926087

Ahora, vamos a generar un vector

In [36]:
#Le indico que tiene 7 elementos, como python empieza en cero en realidad el vector termina en 6
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [38]:
#indicar donde inicia, donde termina y de cuanto en cuanto va
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [39]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [43]:
#Vector de numeros distintos
np.full(10, 6)

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [57]:
#Tenemos que darle una semilla para que sean los mismos numeros aleatorios
np.random.seed(12)

In [58]:
#10 Numeros aleatorios entre 0 y 20
aleatorios = np.random.randint(0, 20, 10)
#guardamos los num en un objeto llamado aleatorios

In [59]:
aleatorios

array([11,  6, 17,  2,  3,  3, 12, 16, 17,  5])

In [61]:
#ordenar los numeros
aleatorios = np.sort(aleatorios)

In [62]:
aleatorios

array([ 2,  3,  3,  5,  6, 11, 12, 16, 17, 17])

In [64]:
#seleccionar en un arregro
aleatorios[4]

6

In [65]:
#con los arreglos si puedo usar comas pero usar doble corchetes
aleatorios[[0,4]]

array([2, 6])

In [67]:
#Seleccionar con condicionales
aleatorios [aleatorios>10]

array([11, 12, 16, 17, 17])

In [68]:
#los que son menores que 10
aleatorios [aleatorios<10]

array([2, 3, 3, 5, 6])

In [69]:
#Dos formas para escribir en python
#nombre de la libreria. funcionque usas. parametros
#Por el metodo

numeros = [1.2, 2.34, 5.18]

1. Hacer arreglo
2. Calcular la media 
3. Redondear a dos decimales

### Por la función

In [70]:
np.array(numeros)

array([1.2 , 2.34, 5.18])

In [72]:
#Para guardar la media
np.mean(np.array(numeros))

2.9066666666666663

In [75]:
round(np.mean(np.array(numeros)),2)

2.91

### Por el método

Se prefiere usar por lo práctico

In [76]:
np.array(numeros).mean().round(2)

2.91